feat: Implemented Scrolling to move between pages
guyluz11/infinite_horizons pull request #110
Opened 2024-06-03 12:41 UTC by M4dhav

Implemented scrolling as required in #4

2024-06-03 13:08 UTC, guyluz11 commented
Have you tested extending scroll physics as I suggested in the issue?
It could be much cleaner and understandable code.

2024-06-03 13:27 UTC, M4dhav commented
Where do you want to pass ScrollPhysics? As far as I can see, IntroductionScreen doesn't have a named parameted scrollPhysics

2024-06-03 15:51 UTC, guyluz11 commented
It exists and already set to not scroll at all 
https://github.com/guyluz11/infinite_horizons/blob/45880dafe208ae303ee9b2e7c311999c5720ea7e/lib/presentation/pages/intro_page.dart#L99

2024-06-03 16:08 UTC, M4dhav commented
Oh! I completely missed that. I'll reimplement this with Scroll Physics

2024-06-09 06:40 UTC, guyluz11 commented
Make sure to also lock the scroll option in the last intro page.
After he clicks the "I am ready" button and there is confetti animation and then he is being redirected to the timer page.

2024-06-24 09:40 UTC, guyluz11 requested changes
Is there any news about the needed progress here?

2024-06-26 14:40 UTC, M4dhav commented
I will get back to it within the week, I already did try with Scroll Physics once before but it had some issues (pages getting stuck between scrolls). I will try and sort them out soon

2024-06-28 13:14 UTC, M4dhav commented
@guyluz11 I've looked into this again and due to lack of documentation and code examples for the implementation of ScrollPhysics that we need, I am unable to sort out the issue that is present during the use of scroll physics. It works but it looks weird and bad. I think the GestureDetector implementation is the best option for us. 
Please let me know how you want to proceed.

2024-06-28 17:42 UTC, guyluz11 commented
ScrollPhysics code shold be cleener and better option, so let me try to implement it as well.
In the mentime feel free work on other issues.

2024-06-28 23:48 UTC, guyluz11 commented
I tried it and managed to make it work, but it looks like the implementation is not as clean as I thought it would be.

So let's proceed with GestureDetector

2024-07-05 07:24 UTC, M4dhav commented
Okay, I will resolve conflicts and get it ready for a merge

2024-07-05 12:33 UTC, guyluz11 commented
> Okay, I will resolve conflicts and get it ready for a merge

Good timing :), I have just pushed another pr and wanting to upload a new version.
Should I wait for this pr?, what is your time estimation.

2024-08-01 10:48 UTC, M4dhav commented
Finally finished, sorry it took this long, College started back up and I have been super busy

2024-08-01 11:59 UTC, guyluz11 requested changes

2024-08-01 11:59 UTC, guyluz11 commented on lib/presentation/pages/intro_page.dart
> +    }
Please remove the else and only call previousPage

2024-08-01 11:59 UTC, guyluz11 commented on lib/presentation/pages/intro_page.dart
> +      }
Add return

2024-08-01 11:59 UTC, guyluz11 commented on lib/presentation/pages/intro_page.dart
> +    if (details.primaryVelocity!.compareTo(0) == -1) {
Change to else if

2024-08-01 11:59 UTC, guyluz11 commented on lib/presentation/pages/intro_page.dart
> +          onHorizontalDragEnd: (DragEndDetails details) =>
Please change to 
onHorizontalDragEnd: onHorizontalDrag

2024-08-01 12:00 UTC, guyluz11 commented
> Finally finished, sorry it took this long, College started back up and I have been super busy

Good to have you back 😌

I hope you are doing great at college

2024-08-01 12:56 UTC, M4dhav commented
> I hope you are doing great at college

5th Semester is quite a bit harder than everything before but I'm handling it pretty well

2024-08-01 13:19 UTC, guyluz11 approved these changes

2024-08-01 13:19 UTC, merged