add missing vibration on the button
guyluz11/infinite_horizons pull request #137
Opened 2024-06-22 08:13 UTC by Amitkumarkoli

pr #117 
Hey! I just add the missing vibration on intro page and ready_for_session_page .
let me know is this correct or not?

2024-06-22 09:38 UTC, guyluz11 requested changes
Welcome to Infinite Horizons.

I have added request for change, please fix and press the re review button for me to start checking the pr again.

2024-06-22 09:38 UTC, guyluz11 commented on lib/presentation/pages/intro_page.dart
> +    }
We are using controllers for api calls.
Use     `VibrationController.instance.vibrate(VibrationType.light);` directly

2024-06-24 04:18 UTC, Amitkumarkoli commented
Hey! I added new changes to it 2 days ago, 
can u please check it and let me know about this?

2024-06-24 09:38 UTC, guyluz11 requested changes
Sorry for the late response, not sure how did I missed it.

2024-06-24 09:38 UTC, guyluz11 commented on lib/presentation/pages/intro_page.dart
> +  }
Not needed as you already called vibration on `ready_for_session_page.dart` which call this method

2024-06-24 09:38 UTC, guyluz11 commented on lib/presentation/pages/ready_for_session_page.dart
> +        },
Would be nicer to extract that to a method

2024-06-25 06:01 UTC, Amitkumarkoli commented
Hey ! I just added new commit let me know this is what u want ?

2024-06-26 09:03 UTC, guyluz11 requested changes

2024-06-26 09:03 UTC, guyluz11 commented on lib/presentation/pages/intro_page.dart
> +  }
Please revert to arrow function

2024-06-26 09:03 UTC, guyluz11 commented on lib/presentation/pages/ready_for_session_page.dart
> +  }
There is no reason to call function to call function??.

Also move it above the `build` method

2024-06-26 09:03 UTC, guyluz11 commented on lib/presentation/pages/ready_for_session_page.dart
> +        () => handleCallback(),
You can write this code cleaner by changing  `() => handleCallback(),`  to just `handleCallback`

2024-06-26 09:04 UTC, guyluz11 requested changes
Also this pr have conflicts with dev branch, please fix it as well

2024-07-05 12:39 UTC, closed without merging