[Resolved] Open resource link externally button
guyluz11/infinite_horizons pull request #170
Opened 2024-07-22 12:46 UTC by Mohit-Joshi-dev

[https://github.com/guyluz11/infinite_horizons/issues/109](https://github.com/guyluz11/infinite_horizons/issues/109)

Added URL launcher on resources page.

![LaunchURL](https://github.com/user-attachments/assets/546564d0-6911-4068-91ce-ca27d21eb9ed)

2024-07-22 12:47 UTC, Mohit-Joshi-dev commented
@guyluz11

2024-07-24 07:24 UTC, guyluz11 requested changes

2024-07-24 07:24 UTC, guyluz11 commented on lib/presentation/pages/tip_resources_page.dart
> +  }
Can you create a controller that calls launchUrl methods?.
Follow the existing controllers as an example.

2024-07-24 07:24 UTC, guyluz11 commented on lib/presentation/pages/tip_resources_page.dart
>          ),
You are missing open url button for the YoutubePlayerPage

2024-07-24 10:06 UTC, Mohit-Joshi-dev commented
@guyluz11 I have completed requested changes

2024-07-24 11:25 UTC, guyluz11 requested changes

2024-07-24 11:25 UTC, guyluz11 commented on lib/infrastructure/url_launcher_repository.dart
> +class _URLLauncherRepository extends URLLauncherController {
Change name to _UrlLauncherRepository

2024-07-24 11:25 UTC, guyluz11 commented on lib/domain/controllers/url_launcher_controller.dart
> +abstract class URLLauncherController {
Change name to UrlLauncherRepository

2024-07-24 11:25 UTC, guyluz11 commented on lib/infrastructure/url_launcher_repository.dart
> +      throw Exception('Could not launch $url');
Let's return bool instead

2024-07-24 11:25 UTC, guyluz11 commented on lib/presentation/pages/tip_resources_page.dart
> +import 'package:infinite_horizons/domain/controllers/url_launcher_controller.dart';
Please export `url_launcher_controller.dart';` from `controllers.dart` and import controllers.dart instead instead

2024-07-25 08:30 UTC, guyluz11 approved these changes

2024-07-25 09:31 UTC, merged