feat: implemented changes as requested in #77
guyluz11/infinite_horizons pull request #81
Opened 2024-05-24 13:57 UTC by M4dhav

Added Spacing as needed, and Title Tile for Settings as needed #77

2024-05-24 16:14 UTC, guyluz11 requested changes
If you can also change the off toggle button colors to something else like gray (outline) from the theme it would be nice :)

2024-05-24 16:14 UTC, guyluz11 commented on lib/presentation/organisms/timer_organism.dart
> +      width: 200,
If we can set it with max width but not minimum like it behaved before that will be nice.

2024-05-24 16:14 UTC, guyluz11 commented on lib/presentation/organisms/timer_organism.dart
> +            text: 'Sound',
Please add translation

2024-05-24 16:14 UTC, guyluz11 commented on lib/presentation/organisms/timer_organism.dart
> +            text: 'Screen Lock',
Please add translations

2024-05-24 16:43 UTC, M4dhav commented
this is how it looks now:
![image](https://github.com/guyluz11/infinite_horizons/assets/114633095/f186b702-e2e1-4221-981c-a3b08afab8b5)
I believe we should add some kind of bounding for the buttons to make it look better, I can either do that with padding or make it responsive using MediaQueries.
Also, I have noticed that the app is not currently responsive at all and we are frequently using absolute integers to set sizes of elements. Do you want to make these responsive in the near future?

2024-05-26 20:57 UTC, guyluz11 requested changes

2024-05-26 20:57 UTC, guyluz11 commented on lib/presentation/atoms/toggle_button_atom.dart
> +        backgroundColor: colorScheme.outline,
Please change the background color to outline only when the toggle is off.

Maybe also the borderColor, test how does it look

2024-05-26 20:57 UTC, guyluz11 commented on lib/presentation/atoms/toggle_button_atom.dart
> +        indicatorColor: colorScheme.primary,
Maybe secondary or tertiary color for off-state will look better.

2024-05-26 21:05 UTC, guyluz11 commented
Regarding the response thing the widgets should not look proportionally the same for all screen sizes.
And currently our main focus is mobile, new features, bug fixes.
So responsive for big screen sizes can wait for now.

Also I didn't find the use of the scale widget in the atoms folder so maybe you meant something else.

2024-05-27 04:45 UTC, M4dhav commented
> Regarding the response thing the widgets should not look proportionally the same for all screen sizes.

Well I mean obviously we don't want them to look the same on a Laptop sized screen for Windows or a Web build but for phones we should still want the apps to look similar I think
> Also I didn't find the use of the scale widget in the atoms folder so maybe you meant something else.
What I meant was that the widgets aren't scaling with the screen, as in they aren't getting bigger or smaller or maintaining their aspect ratio to the screen

2024-05-27 05:03 UTC, M4dhav commented
![image](https://github.com/guyluz11/infinite_horizons/assets/114633095/35c7817d-c0a5-4eb4-8228-dc230cc30fb7)
For the color changes, is this good?

2024-05-27 08:53 UTC, guyluz11 commented
The last one but remove the border-color

2024-05-27 11:45 UTC, guyluz11 commented
Hy, is this pr ready?, it looks good but you didn't press Re-requested review button 

![image](https://github.com/guyluz11/infinite_horizons/assets/9304740/7a8aaff0-832f-4508-971c-96a86966f650)

2024-05-27 12:02 UTC, M4dhav commented
yes, the PR is ready

2024-05-27 12:03 UTC, guyluz11 approved these changes

2024-05-27 12:03 UTC, merged

2024-05-27 12:03 UTC, guyluz11 commented
Can you comment on the issue

I have opened a pr